ALTER TABLE announcements ADD COLUMN views INTEGER NOT NULL DEFAULT 0;
ALTER TABLE posts ADD COLUMN views INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN minecraft_name TEXT;
ALTER TABLE users ADD COLUMN minecraft_uuid TEXT;
